#!/usr/bin/env bash
if [[ ! -e ./nexus-data ]]
then
   mkdir ./nexus-data
fi

echo "docker run!starT!"
docker run --name nexus -d -p 5000:5000 -p 8081:8081 -v ./nexus-data:/nexus-data -u root sonatype/nexus3

echo "get password of admin.password"
cat ./nexus-data/admin.password
